services:
  mysql:
    image: mysql
    ports:
      - '3306:3306'
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_PASSWORD: pass
      MYSQL_USER: app
      MYSQL_DATABASE: app
    networks:
      - mysql
networks:
  mysql: